# -*- coding: utf-8 -*-
"""Week2_Assesment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13yHtjceXsVGcN_qF8Sl_ntURd_9SyiH9

Arithmetic Operators
"""

a=int(input("Enter Number1 : "))
b=int(input("Enter Number2 : "))

print("a + b   = ",a+b)
print("a - b   = ",a-b)
print("a + b   = ",a*b)
print("a / b   = ",a/b)
print("a ** b  = ",a**b)
print("a // b  = ",a//b)

"""Logical Operator"""

p = True
r = False

print("p and r is",p and r)
print("p or r is",p or r)
print("not r is",not r)

"""Assignment Operator"""

s= int(input("Enter Number : "))
s+=9
print("s  += 9  ",  s)
s=s+9
print("s  +  9  ", s)
s-=9
print("s  -= 9  ",  s)
s*=9
print("s  *= 9  ",  s)
s/=9
print("s  /= 9  ",  s)
s %=9
print("s  %= 9  ",  s)
s//=9
print("s  //=9  ",  s)
s**=9
print("s  **=9  ",  s)

"""Identity Operators"""

a = 5
b = 5
x = "Shivu"
y = "Shah"
p = [3,4,5]
q = [3,4,5]
print(a is not b)
print(x is y)
print(x is not y)
print(p is not q)

"""Loops

Nested If-Else
"""

num = int(input("Enter number : "))
if num >=0:
  if num ==0:
    print("Number is 0")
  else:
    print("Number is Positive")
else:
  print("Number is Negative")

"""For Loop"""

num= [2,4,6,8,10]
total=0
for ele in num:
  total = total+ele

print("Sum of even numbers is : ",total)

"""While Loop"""

num = 5
total = 0
s=1

while s<=num:
  total = total +s
  s= s+1
print("Total is : ",total)

"""Range"""

print(list(range(5)))
print(range(10))
print(list(range(3,6)))
print(list(range(2,10,2)))

"""Break Statement"""

for ele in 'Shivani':
  if ele =="n":
    break
  print(ele)

"""Continue Statement"""

for ele in 'Shivani':
  if ele =="n":
    continue
  print(ele)

"""Pass Statement"""

for ele in 'Shivani':
  if ele =="n":
    pass
  print(ele)

"""Membership Operator"""

A= "Shivani Shah"
B={1:'S',2:'h'}

print('w' in A)
print("Shah" not in A)
print(1 in B)
print('v' in A)